### ISSUE TITLE
Error in rule confirm_sexing

### ISSUE THREAD

**Issue by coolkom** [hsigeman/findZX#8]
Hello,

I'm testing the program with the ./test data and almost at the end of the execution I got the errors in the stdout.txt file. I'm also attaching two log files with specific errors.
Do you know why I'm getting this if the ./test data is supposed to run smoothly please ?
Thanks.

Coolkom

[stdout.txt](https://github.com/hsigeman/findZX/files/8852692/stdout.txt)
[plotting_linear.100000bp.log](https://github.com/hsigeman/findZX/files/8852701/plotting_linear.100000bp.log)
[confirm_sexing.mismatch.unfiltered.log](https://github.com/hsigeman/findZX/files/8852702/confirm_sexing.mismatch.unfiltered.log)
.

**Comment by hsigeman** [comment]
Hi Coolkom, 

Thanks for reporting this issue. I think I have fixed the bug now (by specifying that the python script in the "confirm_sexing" rule should be run with python3). Could you try running findZX again with the latest version?

Hope it works this time!
Hanna

**Comment by coolkom** [comment]
Hi Hanna,

Thanks for this really quick reaction. 
Unfortunately I'm still getting the error as you can see from the attached files.
Thanks.

Coolkom.
[stdout2.txt](https://github.com/hsigeman/findZX/files/8853483/stdout2.txt)
[confirm_sexing.mismatch.unfiltered.log](https://github.com/hsigeman/findZX/files/8853484/confirm_sexing.mismatch.unfiltered.log)
[plotting_linear.100000bp.log](https://github.com/hsigeman/findZX/files/8853485/plotting_linear.100000bp.log)

**Comment by hsigeman** [comment]
Hi Coolkom, 

Sorry to hear that the problem persists. 

I have run the test dataset on two different systems but haven't been able to reproduce this error message yet. It would be helpful if you could send me the zipped "howler_monkey_test_dataset" directory so I can check if some of your output files differ from mine. 

Have you tried removing this directory and rerunning the pipeline again? It will probably give the same error message but could be good to double check.

Hanna

**Comment by coolkom** [comment]
Hi Hanna,

Thanks. Here is the folder. I've been running this on a Slurm cluster (but without using the slurm config for snakemake).
Also, on a personal macbook, I managed to run it without error.

Coolkom
[howler_monkey_test_dataset.zip](https://github.com/hsigeman/findZX/files/8859482/howler_monkey_test_dataset.zip)
.

**Comment by hsigeman** [comment]
Hi again,

Thanks a lot for sending the files. 

It seems like the error message is related to the R package ggMarginal. I created a new branch for this issue (https://github.com/hsigeman/findZX/tree/8-error-in-rule-confirm_sexing) with an updated R script. Could you see if this fix works for you?

Hanna

**Comment by coolkom** [comment]
Hi Hanna,

Finally it works great! Thanks for your help to solve this very quickly.

Best,
Coolkom.

**Comment by hsigeman** [comment]
Hi Coolkom, 

Great to hear that it works now! I'll add the fix to the main branch and close this issue. 

Best, 
Hanna
